export const descriptionDictionary = {
    "カリフォルニア・アドベンチャーパーク": "カリフォルニアの多様な文化や自然をテーマにした、アナハイムにあるディズニーパーク",
    "グリフィス天文台": "ロサンゼルスの丘の上にあり、ハリウッドサインとLAの街を一望できる有名な天文台",
    "サルベーション・マウンテン": "カリフォルニア州の砂漠に、愛と信仰をテーマに色彩豊かに描かれた巨大なアート作品", 
    "サンタモニカ": "ロサンゼルス近郊にある、活気あふれる桟橋とビーチが人気", 
    "ブルーマウンテン": "ユーカリの森が広がり、「スリー・シスターズ」と呼ばれる奇岩で知られる、シドニー郊外の世界遺産", 
    "オペラハウス": "シドニーのハーバーに位置する、貝殻のようなユニークなデザインが特徴的な世界的に有名な文化施設", 
    "ブリスベンサイン": "ブリスベン市内のサウス・バンク・パークランドにある、街のシンボルとなっている大きなモニュメント", 
    "コアラサンクチュアリ": "コアラを抱っこできる世界最古かつ最大のコアラ保護区", 
    "グレート・オーシャン・ロード": "切り立った崖と「12使徒」のような奇岩群が続く、オーストラリア南部の世界的に有名な海岸道路", 
    "ハートリーフ島": "グレートバリアリーフにある、ハート型をした珊瑚礁のことで、上空からしか見ることができない特別なスポット",  
    "ロットネスト島": "パース沖にある、フレンドリーな笑顔の「クオッカ」が生息することで知られる美しい島", 
    "インド門": "ムンバイの港に建つ、植民地時代の歴史を持つ巨大な凱旋門", 
    "タージマハル": "インド北部アグラにある、ムガル帝国皇帝が愛妃のために建てた、白亜の美しい霊廟",
    "モナス": "ジャカルタ中心部のムルデカ広場にそびえる、炎のオブジェが特徴的な独立を象徴する塔", 
    "インドネシア国立美術館": "インドネシアの豊かな歴史と文化を紹介する、ジャカルタで最も重要な博物館", 
    "ストリートフード": "手軽で安価に現地の味を楽しめる、屋台などで提供される多様な料理",
    "バトゥ洞窟": "巨大な黄金のヒンドゥー教の神像と、272段のカラフルな階段が特徴的な洞窟寺院", 
    "クアラルンプール・シティ・ギャラリー": "「I ♡ KL」のモニュメントで有名で、街の歴史や未来の都市計画をジオラマで紹介するギャラリー", 
    "ペトロナス・ツインタワー": "スカイブリッジで結ばれた2本の高層ビルで、クアラルンプールの象徴として知られる世界有数のタワー", 
    "モアルボアル": "ダイビングで有名な、フィリピンのセブ島にある美しい海辺の町", 
    "チャンギ国際空港": "チャンギ国際空港にある、世界一の高さを誇る室内滝「HSBCレイン・ヴォーテックス」",
    "ガーデンズ・バイ・ザ・ベイ": "シンガポールの近未来的な植物園で、巨大な人工ツリー「スーパーツリー」が夜にライトアップされることで有名",
    "ホーカー": "街中にある、多種多様な屋台が集まり、安価に現地のグルメを楽しめるフードコート", 
    "マーライオン": "シンガポールのシンボルである、上半身がライオン、下半身が魚の姿をした伝説上の生き物の像", 
    "アユタヤ遺跡": "タイのかつての都だった場所で、仏頭が木の根に覆われた仏像など、歴史的な仏教遺跡が数多く残る場所", 
    "カオサン通り": "世界中のバックパッカーが集まる、安宿や屋台、バーがひしめく活気あふれるバンコクの通り", 
    "ワットアルン": "チャオプラヤー川沿いにそびえる、美しい陶磁器の装飾が施された仏教寺院", 
    "ワットパクナム": "巨大な金色の仏像が特徴的な、タイのバンコク郊外にある寺院", 
    "ドンコイ通り": "ホーチミンの中心部にある、歴史的建造物や高級ブランド店が並ぶ、賑やかな商業ストリート", 
    "メコン川": "東南アジアを流れ、肥沃なデルタ地帯を形成し、人々の暮らしを支える大河", 
    "戦争博物館": "ベトナム戦争の歴史や悲惨さを伝える資料や展示物が収蔵されている博物館"
};

export const imageDictionary = {
    "カリフォルニア・アドベンチャーパーク": "./images/america/adventure-park.jpg",
    "グリフィス天文台": "./images/america/griffith-observatory.jpg",
    "サルベーション・マウンテン": "./images/america/salvation-mountain.jpg", 
    "サンタモニカ": "./images/america/santa-monica.jpg", 
    "ブルーマウンテン": "./images/australia/blue-mountain.jpg", 
    "オペラハウス": "./images/australia/opera-house.jpg", 
    "ブリスベンサイン": "./images/australia/brisbane-sign.jpg", 
    "コアラサンクチュアリ": "./images/australia/lone-pine-koala.jpg", 
    "グレート・オーシャン・ロード": "./images/australia/great-ocean-road.jpg", 
    "ハートリーフ島": "./images/australia/heart-leaf-island.jpg",  
    "ロットネスト島": "./images/australia/lottnest-island.jpg", 
    "インド門": "./images/india/india-gate.jpg", 
    "タージマハル": "./images/india/taj-mahal.jpg",
    "モナス": "./images/indonesia/national-monument.jpg", 
    "インドネシア国立美術館": "./images/indonesia/national-galary.jpg", 
    "ストリートフード": "./images/indonesia/street-food.jpg",
    "バトゥ洞窟": "./images/malaysia/batu-caves.jpg", 
    "クアラルンプール・シティ・ギャラリー": "./images/malaysia/city-galary.jpg", 
    "ペトロナス・ツインタワー": "./images/malaysia/petronas-twin-towers.jpg", 
    "モアルボアル": "./images/phillipines/moalboal.jpg", 
    "チャンギ国際空港": "./images/singapore/changi-airport-fountain.jpg",
    "ガーデンズ・バイ・ザ・ベイ": "./images/singapore/gardens-by-the-bay.jpg",
    "ホーカー": "./images/singapore/hawker-centre.jpg", 
    "マーライオン": "./images/singapore/marlion.jpg", 
    "アユタヤ遺跡": "./images/thailand/ayutthaya.jpg", 
    "カオサン通り": "./images/thailand/khao-san-road.jpg", 
    "ワットアルン": "./images/thailand/wat-arun.jpg", 
    "ワットパクナム": "./images/thailand/wat-paknam.jpg", 
    "ドンコイ通り": "./images/vietnam/dong-khoi-street.jpg", 
    "メコン川": "./images/vietnam/mecon-river.jpg", 
    "戦争博物館": "./images/vietnam/war-museum.jpg"
};

export const countryImage = {
    "アメリカ": "./images/america/america.jpg",
    "オーストラリア": "./images/australia/australia.jpg",
    "インド": "./images/india/india.jpg",
    "インドネシア": "./images/indonesia/indonesia.jpg",
    "マレーシア": "./images/malaysia/malaysia.jpg",
    "フィリピン": "./images/phillipines/phillipines.jpg",
    "シンガポール": "./images/singapore/singapore.jpg",
    "タイ": "./images/thailand/thailand.jpg",
    "ベトナム": "./images/vietnam/vietnam.jpg"
}